[package]
name = "cangrebot"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Meneses <sergioalmeneses@gmail.com>", "Daniel Solarte <contact@danielsolarte.com>"]
description = "A Discord Bot made with Rust from RustLangEs Community"
readme = "README.md"

[dependencies]
anyhow = "1.0.66"
shuttle-serenity = "0.42.0"
shuttle-runtime = "0.42.0"
serenity = { version = "0.12.1", default-features = true, features = ["cache", "framework", "client", "gateway", "rustls_backend", "model", "standard_framework", "voice"] }
#shuttle-secrets = "0.42.0"
tokio = "1.26.0"
tracing = "0.1.37"
color-eyre = "0.6.2"
serde = "1.0.188"
serde_json = "1.0.105"
songbird = { version = "0.4.1", features = ["serenity"] }
#shuttle-static-folder = "0.42.0"
reqwest = { version = "0.12.2", features = ["json"] }
scraper = { version = "0.19.0", features = ["indexmap", "deterministic", "atomic"] }
plantita_welcomes = { git = "https://github.com/CrawKatt/plantita_welcomes.git" }
image = "0.24.7"

[dependencies.parking_lot]
version = "0.12"
features = ["send_guard"]