[package]
name = "cangrebot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
shuttle-serenity = "0.24.0"
shuttle-runtime = "0.24.0"
serenity = { version = "0.11.5", default-features = true, features = ["client", "gateway", "rustls_backend", "model", "standard_framework"] }
shuttle-secrets = "0.24.0"
tokio = "1.26.0"
tracing = "0.1.37"
color-eyre = "0.6.2"
serde = "1.0.188"
serde_json = "1.0.105"
