name: Deploy

on:
  push:
    branches:
      - "main"
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # fetch submodules recursively
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: shuttle-hq/deploy-action@main
        env:
          LITCRYPT_ENCRYPT_KEY: ${{ secrets.LITCRYPT_ENCRYPT_KEY }}
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          allow-dirty: "true"
          no-test: "true"
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            GUILD_ID = '${{ secrets.GUILD_ID }}'
